export const LOGIN_LOADING = 'LOGIN_LOADING';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const ADD_FRIEND_LOADING = 'ADD_FRIEND_LOADING';
export const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
