exports.GET_CURRENT_MESSAGES = 'GET_CURRENT_MESSAGES';
exports.RECEIVE_CURRENT_MESSAGES = 'RECEIVE_CURRENT_MESSAGES';
exports.GET_IS_FRIEND_TYPING = 'GET_IS_FRIEND_TYPING';
exports.RECEIVE_IS_FRIEND_TYPING = 'RECEIVE_IS_FRIEND_TYPING';
exports.SET_USER_TYPING = 'SET_USER_TYPING';
exports.SET_USER_NOT_TYPING = 'SET_USER_NOT_TYPING';
exports.SEND_MESSAGE = 'SEND_MESSAGE';
