export const GET_CURRENT_MESSAGES = 'GET_CURRENT_MESSAGES';
export const RECEIVE_CURRENT_MESSAGES = 'RECEIVE_CURRENT_MESSAGES';
export const GET_IS_FRIEND_TYPING = 'GET_IS_FRIEND_TYPING';
export const RECEIVE_IS_FRIEND_TYPING = 'RECEIVE_IS_FRIEND_TYPING';
export const SET_USER_TYPING = 'SET_USER_TYPING';
export const SEND_MESSAGE = 'SEND_MESSAGE';
