export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
